# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: ^tests/(cassettes|__snapshots__)/.+\.(yaml|ambr)$
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      # - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # - id: name-tests-test
      #   args: [--pytest-test-first]
      #   exclude: ^workspaces/.+/tests/(factories|fakes).py$
      - id: trailing-whitespace
        types: [python]

  # change to use yamlfix or prettier
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --preserve-quotes
          - --indent=2
          - --offset=2
        exclude: ^tests/cassettes/.+\.yaml$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.17.0
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.2.4
    hooks:
      - id: conventional-gitmoji

  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.4
    hooks:
      - id: pdm-lock-check

  - repo: local
    hooks:
      - id: ruff
        name: Fix with ruff
        entry: ruff
        args: ["--extend-fixable=ERA001,F401,F841"]
        require_serial: true
        language: system
        types: [python]

      - id: ruff
        name: Format with ruff
        entry: ruff format
        require_serial: true
        language: system
        types: [python]
